spring:
  datasource:
    url: jdbc:mysql://localhost:3308/chat-db
    username: myuser
    password: mypassword

logging:
  level:
    root: INFO
    org.springframework.web.socket: DEBUG
    org.springframework.web.socket.handler: DEBUG
    org.springframework.web.socket.server: DEBUG
    org.springframework.messaging: DEBUG
